package com.example.split.entity;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

public class User {
    private String name;                        // Display Name
    private String email;                       // Email
    private String password;                    // Plaintext for now
    private String phone;                       // Phone Number

    private String userID;                      // Uid generated by Firebase after instantiation
    private List<Expense> expenseList;         // List of expenses

    public User() {}

    public User(String name, String email, String phone, String password) {
        this.name = name;
        this.email = email;
        this.password = password;
        this.phone = phone;
    }

    public String getName() { return name; }
    public String getEmail() { return email; }
    public String getPhone() { return phone; }
    public void edit_name(String name) { this.name = name; }
    public void edit_email(String email) { this.email = email; }
    public void edit_phone(String phone) { this.phone = phone; }


    public void setUserId(String userID) { this.userID = userID; }
    public String getUserId() { return userID; }

    public Map<String, Object> toMap() {
        HashMap<String, Object> result = new HashMap<>();
        result.put("userId", userID);
        result.put("name", name);
        result.put("email", email);
        result.put("password", password);
        result.put("phone", phone);

        return result;
    }

}
